name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Configure npm for Volvo Azure Artifacts
      run: |
        echo "@volvo:registry=https://pkgs.dev.azure.com/volvogroup/_packaging/VES/npm/registry/" >> ~/.npmrc
        echo "//pkgs.dev.azure.com/volvogroup/_packaging/VES/npm/registry/:username=AzureDevOps" >> ~/.npmrc
        echo "//pkgs.dev.azure.com/volvogroup/_packaging/VES/npm/registry/:_password=$(echo -n ${{ secrets.VOLVO_PAT }} | base64)" >> ~/.npmrc
        echo "always-auth=true" >> ~/.npmrc
    - run: npm ci
    - run: npm run lint
