name: Old Search Connector - Upsert

on: 
  repository_dispatch:
    types:
      - resource-published

jobs:
  check-event-status:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Path: ${{ github.event.client_payload.path }}"

  notify-connector:
    if: (github.event.client_payload.status == 200 || github.event.client_payload.status == 204) && endsWith(github.event.client_payload.path, '.md')
    runs-on: ubuntu-latest
    env:
      OLD_CONNECTOR_DOMAIN: ${{ vars.OLD_CONNECTOR_DOMAIN }}
      WEBSITE_NAME: ${{ vars.WEBSITE_NAME }}
      OLD_API_KEY: ${{ secrets.OLD_API_KEY }}
    steps:
      - name: Notify upsert endpoint
        run: |
          sleep 1s
          PAGE_PATH=$(echo "${{ github.event.client_payload.path }}" | sed 's/\.md$//g')
          URI="${OLD_CONNECTOR_DOMAIN}/$WEBSITE_NAME"
          BODY='{ "paths": [ "'$PAGE_PATH'" ] }'
          BODY="$(echo "$BODY" | jq -c)"
          # Capture both response and HTTP status code
          response=$(curl -s -w "%{http_code}" -o response_body.txt -H "x-api-key: $OLD_API_KEY" -X POST "$URI" -d "$BODY")
          http_code="${response: -3}"
          body=$(cat response_body.txt)
          echo "HTTP status: $http_code"
          echo "response: $body"
          # Accept any 2xx HTTP status code as success
          if [[ ! "$http_code" =~ ^2[0-9][0-9]$ ]]; then
            echo "API call failed with status $http_code"
            exit 1
          fi
        shell: bash

  status-checker:
    needs: notify-connector
    runs-on: ubuntu-latest
    if: always()
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Notify on connector failure in Slack
        if: ${{ needs.notify-connector.result != 'success' }}
        run: |
          path="${{ github.event.client_payload.path }}"
          site="${{ github.event.client_payload.site }}"
          repo="${{ github.repository }}"
          run_url="https://github.com/${repo}/actions/runs/${{ github.run_id }}"
          payload="{
            \"text\": \":x: *Search Connector FAILED!*\nSite: $site\nPath: $path\n<${run_url}|View workflow run>\"
          }"
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
      - name: Connector job succeeded or no Slack notification required
        if: ${{ needs.notify-connector.result == 'success' }}
        run: |
          echo "Notify connector job succeeded. No Slack notification sent."
          echo "Path: ${{ github.event.client_payload.path }}"
          echo "Status: ${{ needs.notify-connector.result }}"
